        <!-- Start Main Content -->
        <div class="main-content">
        <div class="container">
        <div class="row">
        <div class="col-md-8">
        <h2><?php echo $this->pageInfo["pageTitle"] ?></h2>
        <div class="separator">
        </div>
        
        <p><?php echo $this->pageInfo["content"] ?></p>
        </div>
        
        <div class="col-md-4">
        <div class="sidebar">
        <div class="widget">    
        <h3 class="sidebar-title">Latest Stories</h3>      
        <div id="nt-container">
        
        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FThe-Brothers-Travel-422903684778178%2F&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
      <!--   <ul id="nt">
            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div>
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div>
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div>
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div>
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div>
            </a>
            </li>
            
        </ul> -->
       
    </div>
    </div><!-- .widget -->
    <div class="widget">
        <h3 class="sidebar-title">Book Now</h3>

        <div class="single-product">
        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
            <div class="icon">

            </div>
            <div class="desc">
                <h4>Chandigarh-New Delhi</h4>
                <p>Best fares for New Delhi </p>
                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
            </div>
            </div>
        </div><!-- .widget -->
    </div><!-- .sidebar -->
    </div><!-- .col-sm-4 -->

    </div>
    </div>
    </div>
