<!-- Page Content -->
  <div id="content">
    <div class="container">

        <div class="row">
            <div id="main-content">
                <article>
        <header>
        <h1>ABOUT US</h1>
        <div class="sep"><i class="fa fa-car"></i></div>
        </header>
               <div class="center-content"><p>Thank you very much for taking the time to visit our website.</p>
<p>
we have always delivered a highly professional, cost-effective, 
and courteous travel planning service whenever called upon. We feel that we have accomplished this goal with 
excellent results for our clients.
We have well experienced and educated drivers. They know about every culture and history tours, 
well respected locals guides, possessing vast knowledge of the cities.
</p>
<p>We wish you many great vacations and travel experiences!</p></div>
         
         
         </div><!-- /.col-sm-3 -->
         
         
         
         </div><!-- /. row -->
         
          
         
         </div>
         
         
        </article>
            </div>