        <!-- Start Main Content -->
        <div class="main-content">
        <div class="container">
        <div class="row">
        <div class="col-md-8">
        <h2>ABOUT US</h2>
        <div class="separator">
        </div>
        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" class="align-left" width="250" />
        <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message.</p>
        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c3.jpg" class="align-right" width="250" />
        <p>This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>

        <p>This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>

        <p>This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
        </div>
        
        <div class="col-md-4">
        <div class="sidebar">
        <div class="widget">    
        <h3 class="sidebar-title">Latest News</h3>      
        <div id="nt-container">
        
        <ul id="nt">
            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div><!-- News Item -->
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div><!-- News Item -->
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div><!-- News Item -->
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div><!-- News Item -->
            </a>
            </li>

            <li>
                <a href="#">
                <div class="news-item">
                <div class="news-img">
                    <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" />
                    </div>
                    
                <div class="news-text">
                    <h4>Latest News 1</h4>
                    <p>News updates Best fares for New Delhi</p>
                    </div>
                
                </div><!-- News Item -->
            </a>
            </li>
            
        </ul>
       
    </div>
    </div><!-- .widget -->
    <div class="widget">
        <h3 class="sidebar-title">Book Now</h3>

        <div class="single-product">
        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
            <div class="icon">

            </div>
            <div class="desc">
                <h4>Chandigarh-New Delhi</h4>
                <p>Best fares for New Delhi </p>
                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
            </div>
            </div>
        </div><!-- .widget -->
    </div><!-- .sidebar -->
    </div><!-- .col-sm-4 -->

    </div>
    </div>
    </div>
