 <!-- Page Content -->
  <div id="content">
    <div class="container">

        <div class="row">
            <div id="main-content">
                <article>
        <header>
        <h1>Book Now</h1>
        <div class="sep"><i class="fa fa-car"></i></div>
        </header>
               <div class="center-content"><p> PLEASE PUT YOUR RIDE HERE</p></div>
         <div class="cars-list">
         
         <div class="row">
         
         <div class="col-sm-3">
         
        </div><!-- /.col-sm-3 -->
        <strong>
<div class='wrap columns-2' id='pageList'>
<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
<br><div class ="mainpage-content-colorbox success">
<?php if($this->messageSuccess!=''){?>
<span class="success"><?php echo $this->messageSuccess; ?></span>
<?php }?>
<?php if($this->messageError!=''){?>
<span class="error"><?php echo $this->messageError; ?></span>
<?php } ?>
</div>
<?php 
}?> 
</div>         

</strong>
         <div class="col-sm-6">
         
         <form validate  name="bookfrm" id="bookfrm" method="POST" action="<?php echo HTTP_PATH; ?>index/booking">
  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    <input type="text" class="form-control" name="name" id="exampleInputEmail1" placeholder="Name" required>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Email" required>
  </div>
  
  <div class="form-group">
    <label for="exampleInputPassword1">Phone No</label>
    <input type="tel" class="form-control"  name="phone" id="exampleInputPassword1" placeholder="Phone No" required>
  </div>

  <div class="form-group">
    <label for="exampleInputPassword1">Address</label>
    <textarea name="address" class="form-control" id="exampleInputPassword1" placeholder="Address" required></textarea>
  </div>

  <div class="form-group">
    <label for="exampleInputPassword1">Travel Date</label>
       <div class='input-group date' id='datetimepicker1'>
          <input name="travelDate" type='text' id="travelDate" class="form-control"  required/>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>

  </div>

   <div class="form-group">
    <label for="exampleInputPassword1">Return Date</label>
       <div class='input-group date' id='datetimepicker2'>
          <input  name="returnDate" type='text' class="form-control"  id="returnDate" required/>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
       
  </div>

  <div class="form-group">
    <label for="exampleInputPassword1">Quantity Member</label>
    <input type="number" name="quantity" class="form-control" id="exampleInputPassword1" placeholder="Quantity Member" required>
    <span class="sm-sizeing">12 Years old child will consider as one adult.</span>
  </div>
  
  <div class="form-group">
    <label for="exampleInputPassword1">Pickup Location</label>
    <input type="text" name="pickup_location" class="form-control" id="exampleInputPassword1" placeholder="Pickup Location" required>
  </div>
 
  <div class="form-group">
    <label for="exampleInputPassword1">Desination </label>
    <input type="text" name="desination" class="form-control" id="exampleInputPassword1" placeholder="Desination " required>
  </div>
  
  <div class="form-group">
  <label for="sel1">Category:</label>
  <select name="catg" class="form-control" id="sel1" required>
    <option value="">Select Car</option>
    <?php foreach ($this->category as $key => $value) { ?>
    <option value="<?php echo $value["id"]; ?>"><?php echo $value["name"]; ?></option>
    <?php } ?>
  </select>
</div>

   
  <!-- <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div> -->
  <div  class="contact-us-btn">
  <button type="submit"  class="btn btn-default">Submit</button>
  </div>
</form>
        
         <div class="book-now">
         
         <div class="car-text">
         
         
         
         </div>
         
         </div>
         
         
         </div><!-- /.col-sm-3 -->
         
         </div><!-- /. row -->
         
          
         
         </div>
         
         
        </article>
            </div>
      
        </div>
        <!-- /.row -->

    </div> <!-- /.container -->
  </div>

 <script type="text/javascript">
     $(function () {
          $('#datetimepicker1').datetimepicker();
           $('#datetimepicker2').datetimepicker();
      });

  </script>