
<?php 
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/front_end/vendor/jquery-ui.css" );
      $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/vendor/jquery-ui.js" );

?>


<?php $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/booking.js" ); ?>
<!-- Start Main Content -->
    <div class="main-content">

<div class='wrap columns-2' id='profile'>
    <?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
    <br>
    <?php if($this->messageSuccess!=''){?>
    <div class ="alert alert-success success"><?php echo $this->messageSuccess; ?></div>
    <?php }?>
    <?php if($this->messageError!=''){?>
    <div class ="alert alert-danger success"><?php echo $this->messageError; ?> </div>
    <?php } ?>
   
    <?php 
    }?> 
</div>   


    <div class="container">
    <div class="row justify-content-center">
    <div class="col-md-8">
    <div class="sidebar">
    <form autocomplete="off" validate action="/index/booking" method="POST" id="booking" name="booking">

<div class="booking-type">

  <div class="btn-group btn-toggle"> 
    <button class="btn btn-lg btn-default" value="train">Train</button>
     <input type="hidden" id="travelType" name="travelType" value="plane">
    <button class="btn btn-lg btn-primary active" value="plane">Flight</button>
  </div>
  
</div>
    <div class="widget contactForm">  
    <h3 class="sidebar-title req">Booking Info</h3>   
    
      <div class="single-input">
        <label for="fromLocation">Departure Station/City</label>
          <input type="text" id="SearchAirport" name="departure" aria-describedby="emailHelp" placeholder="e.g. New York" required>
        
      </div>
        <div class="single-input">
        <label for="toLocation">Arrival Station/City</label>
          <input type="text" id="findAirport" name="arrival" aria-describedby="emailHelp" placeholder="e.g Albama" required>
             
      </div>    
      <div class="single-input">
      
      <div class="row">
        <div class="col-sm-6">
          <label for="departDate">Depart Date</label>
            <input type="date" id="departureDate" name="departureDate" aria-describedby="emailHelp" placeholder="" required>
        </div>

        <div class="col-sm-6">
          <label for="returnDate">Return Date</label>
            <input type="date" id="returnDate" name="returnDate" placeholder="">
        </div>
      </div>

      </div>
      <div class="single-input">
        
        <div class="row">
        <div class="col-sm-4">
          <label for="adult">Adult</label>
            <input type="number" id="adult" name="adult" aria-describedby="emailHelp" placeholder="" required>
        </div>

        <div class="col-sm-4">
          <label for="child">Child</label>
            <input type="number" id="child" name="child" aria-describedby="emailHelp" placeholder="">
        </div >

        <div class="col-sm-4">
          <label for="infant">Infant</label>
            <input type="number" id="infant" name="infant" aria-describedby="emailHelp" placeholder="">
        </div>
      </div>

      </div>

      <h3 class="sidebar-title req mt-5">Perosnal Info</h3> 

      <div class="single-input">
      <label for="firstName">Sex</label>
          <select class="form-control" name="gender" id="gender">
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>
      </div>

      <div class="single-input">
      <label for="firstName">First Name</label>
          <input type="text" id="firstName" value="<?php echo $this->user["firstName"] != "" ? $this->user["firstName"] : ""; ?>" name="firstName" aria-describedby="firstNameHelp" placeholder="First name" required>
      </div>
      <div class="single-input">
      <label for="lastName">Last Name</label>
          <input type="text" id="lastName" name="lastName" value="<?php echo $this->user["lastName"] != "" ? $this->user["lastName"] : ""; ?>" aria-describedby="lastNameHelp" placeholder="Last Name" required>
      </div>

      <div class="single-input">
      <label for="email">Email Address</label>
          <input value="<?php echo $this->user["email"] != "" ? $this->user["email"] : ""; ?>" type="email" id="email" name="email" aria-describedby="emailHelp" placeholder="email@example.com" required>
      </div>

      <div class="single-input">
      <label for="phoneNumber">Mobile Number</label>
          <input value="<?php echo $this->user["phonenumber"] != "" ? $this->user["phonenumber"] : ""; ?>" type="number" id="phoneNumber" name="phoneNumber" aria-describedby="phoneNumberHelp" placeholder="+91-000-000-0000" required>
      </div>              
            <div class="single-input">
              <label for="address">Address</label>
        <textarea  id="address" name="address" aria-describedby="addressHelp" placeholder="Address" required>
          <?php echo $this->user["address"] != "" ? $this->user["address"] : ""; ?>
        </textarea>
      </div>

      <div class="single-input">
        
        <div class="row">
        
       <!--  <div class="col-sm-6">
          <label for="city">City</label>
            <input required type="text" id="city" name="city" aria-describedby="cityHelp" placeholder="">
        </div>

        <div class="col-sm-3">
          <label for="state">State</label>
            <input type="text" required id="state" name="state" aria-describedby="stateHelp" placeholder="">
        </div> -->

        <div class="col-sm-3">
          <label for="infant">Zip</label>
            <input required value="<?php echo $this->user["zipcode"] != "" ? $this->user["zipcode"] : ""; ?>" type="number" id="zipcode" name="zipcode" aria-describedby="emailHelp" placeholder="">
        </div>
      </div>

      </div>

      <div class="d-flex justify-content-start single-button">
        <button type="submit" class=" primary-btn d-inline-flex text-uppercase align-items-center">Book Now<span class="lnr lnr-arrow-right"></span></button>
      </div>              
  

    </div><!-- .widget -->
  

  </form>
  </div><!-- .sidebar -->
  </div><!-- .col-sm-4 -->

  </div>
  </div>
  </div>
    
    <!-- End Main Content -->

  <script type="text/javascript" charset="utf-8" async defer>
   
$('.btn-toggle').click(function() {
    $(this).find('.btn').toggleClass('active');  
    
    if ($(this).find('.btn-primary').size()>0) {
      $(this).find('.btn').toggleClass('btn-primary');
    }
    
    $(this).find('.btn').toggleClass('btn-default');
       
});
  </script>  

<script src="<?php echo PUBLIC_PATH.'js/front_end/' ; ?>bootstrap-select.min.js"></script>