<!-- Start Main Content -->
    <div class="main-content">
    <div class="container">
    <div class="row">
    <div class="col-md-6">
    <div class="widget">
    <!-- <h3 class="sidebar-title">Address</h3>   -->
      <h5><i class="fa fa-map-marker" aria-hidden="true"></i>Address</h5>
    <p>The brothers travel agency<br> Jalandher</p>
    <h5><i class="fa fa-phone" aria-hidden="true"></i>Phone</h5>
    <p><a href="tel:+918968325322" title="+91-896-832-5322">+91-896-832-5322</a>
    <h5><i class="fa fa-envelope" aria-hidden="true"></i>Email Address</h5>
    <a href="mailto:travelbrotherstour@gmail.com">travelbrotherstour@gmail.com</a>


    </div><!-- .widget -->
    </div>
    
    <div class="col-md-6">
    <div class="sidebar">
    
    <div class="google-map"><iframe src="https://www.google.com/maps/embed?q=jalandher" width="600" height="350" frameborder="0" style="border:0" allowfullscreen></iframe></div>
    <!-- <div class="widget contactForm">  
    <h3 class="sidebar-title req">Request a Quote</h3>    
    
    <form>
      <div class="single-input">
                <input type="text" name="fname" placeholder="Full Name">
              </div>
        <div class="single-input">
                <input type="email" name="email" placeholder="Email Address">
              </div>    
      <div class="single-input">
      <input type="text" name="your-phone" placeholder="Phone Number (Required)">
      </div>
      <div class="single-input">
      <input type="text" name="your-location" placeholder="City/Town (Required)">
      </div>
      <div class="single-input">
                <input type="text" name="insurancetype" placeholder="Insurance Type" >
              </div>
      <div class="single-input">
                <input type="text" name="how did you find us" placeholder="How Did You Find Us" >
              </div>              
            <div class="single-input">
                <textarea name="message" placeholder="Type your message here..." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Type your message here...'" required=""></textarea>
              </div>
      <div class="d-flex justify-content-start single-button">
        <button class=" primary-btn d-inline-flex text-uppercase align-items-center">Send Message<span class="lnr lnr-arrow-right"></span></button>
      </div>              
    </form>

    </div> -->
  
  </div>
  </div>

  </div>
  </div>
  </div>