<!-- Start Main Content -->
    <div class="main-content">
    <div class="container">
    <div class="row">
    <div class="col-md-6">
    <div class="widget">
    <h3 class="sidebar-title">Address</h3>  
      <h5><i class="fa fa-map-marker" aria-hidden="true"></i>Address</h5>
    <p>1070 Suffield Street<br> Agawam, MA 01001</p>
    <h5><i class="fa fa-phone" aria-hidden="true"></i>Phone</h5>
    <p><a href="tel:1-413-781-2410">(413) 781-2410</a><br> <a href="tel:1-800-243-8134">(800) 243-8134</a> (Toll Free)</p>
    <h5><i class="fa fa-envelope" aria-hidden="true"></i>Email Address</h5>
    <a href="mailto:yourdomain@gmail.com">yourdomain@gmail.com</a>


    </div><!-- .widget -->
    </div>
    
    <div class="col-md-6">
    <div class="sidebar">
    
    <div class="google-map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2962.5233447679225!2d-72.63718218455342!3d42.05340047920856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e6e394f060ae7f%3A0xc90b7c515dfc7690!2s1070+Suffield+St%2C+Agawam%2C+MA+01001%2C+USA!5e0!3m2!1sen!2sin!4v1516179191469" width="600" height="350" frameborder="0" style="border:0" allowfullscreen></iframe></div>
    <!-- <div class="widget contactForm">  
    <h3 class="sidebar-title req">Request a Quote</h3>    
    
    <form>
      <div class="single-input">
                <input type="text" name="fname" placeholder="Full Name">
              </div>
        <div class="single-input">
                <input type="email" name="email" placeholder="Email Address">
              </div>    
      <div class="single-input">
      <input type="text" name="your-phone" placeholder="Phone Number (Required)">
      </div>
      <div class="single-input">
      <input type="text" name="your-location" placeholder="City/Town (Required)">
      </div>
      <div class="single-input">
                <input type="text" name="insurancetype" placeholder="Insurance Type" >
              </div>
      <div class="single-input">
                <input type="text" name="how did you find us" placeholder="How Did You Find Us" >
              </div>              
            <div class="single-input">
                <textarea name="message" placeholder="Type your message here..." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Type your message here...'" required=""></textarea>
              </div>
      <div class="d-flex justify-content-start single-button">
        <button class=" primary-btn d-inline-flex text-uppercase align-items-center">Send Message<span class="lnr lnr-arrow-right"></span></button>
      </div>              
    </form>

    </div> -->
  
  </div>
  </div>

  </div>
  </div>
  </div>