 <!-- Page Content -->
  <div id="content">
    <div class="container">

        <div class="row">
            <div id="main-content">
                <article>
        
                <div class="cars-list">
         
         <div class="row">
         
         <div class="col-sm-6">
         <div class="Company-Address">
         
         <h3>Raftaar Tour & Travel<br> 
                   Owner Yogesh<br> 
                   House No. 145<br>
                   Ram Galli Mission Road<br> 
                Pathankot, Pin : 145001 (PUNJAB)<br>
                Phone No : +919464545786 | +919915041417<br>
                Email : kumaryogesh399@gmail.com       
           <h3>
        </div>
 <!--  <div class="contact-form">     
 <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Phone</label>
    <input type="tel" class="form-control" id="exampleInputEmail1" placeholder="Phone">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Massage</label>
    <input type="textarea" class="form-control" id="exampleInputEmail1" placeholder="Massage">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>     -->
    </div><!-- /.col-sm-3 -->
         
         <div class="col-sm-6">
       
       <!--   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d109782.86712308136!2d76.62733983194056!3d30.698305207282406!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee906da6f81f%3A0x512998f16ce508d8!2sMission+Rd,+Pathankot,+Punjab+145001!5e0!3m2!1sen!2sin!4v1491902435315" width="550" height="500" frameborder="0" style="border:0" allowfullscreen></iframe> -->

       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3373.345480069252!2d75.66531371478176!3d32.27568828112623!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x391c7f9fcbdecf63%3A0xdc83c765fb289236!2sMission+Rd%2C+Pathankot%2C+Punjab+145001!5e0!3m2!1sen!2sin!4v1493660603344" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
         
         </div><!-- /.col-sm-3 -->
         
          </div><!-- /. row -->
         
         </div>
         
        </article>
            </div>
      
        </div>
        <!-- /.row -->

    </div> <!-- /.container -->
  </div>