        <!-- Start About Area -->
        <section id="home-boxs" class="section-full gray-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <figure class="single-service">
                            <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c1.png" class="img-fluid" alt="">
                            <figcaption class="text-center">
                                <h5 class="text-uppercase">Addiction Whit Gambling</h5>
                                <p>It is a good idea to think of your PC as an office. It stores files, programs, pictures. This can be compared to an actual office’s files</p>
                                <a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW<span class="lnr lnr-arrow-right"></span></a>
                            </figcaption>
                        </figure>
                    </div>
                    <div class="col-md-4">
                        <figure class="single-service">
                            <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c2.jpg" class="img-fluid" alt="">
                            <figcaption class="text-center">
                                <h5 class="text-uppercase">Headset No Longer Wired</h5>
                                <p>If you are in the market for a computer, there are a number of factors to consider. Will it be used for your home, your office or perhaps </p>
                                <a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW<span class="lnr lnr-arrow-right"></span></a>
                            </figcaption>
                        </figure>
                    </div>
                    <div class="col-md-4">
                        <figure class="single-service">
                            <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c3.jpg" class="img-fluid" alt="">
                            <figcaption class="text-center">
                                <h5 class="text-uppercase">Life Advice Looking At Window</h5>
                                <p>Having a baby can be a nerve wrackingexp erience for new parents – not the nine months of pregnancy, I’m talking</p>
                                <a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW<span class="lnr lnr-arrow-right"></span></a>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            </div>
        </section>
        <!-- End About Area -->
        <!-- Start Product Area -->
        
        <section id="about-us" class="bg-dark section-full">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="section-title text-center">
                            <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/ts3.png" class="img-fluid">
                            <p class="text-uppercase">WHAT WE ARE</p>
                            <h3>Plantronics with its GN Netcom <b>wireless headset</b> creates the next generation of wireless headset and other products such as wireless amplifiers, and <b>wireless headset</b> telephone.</h3>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="services" class="title-bg section-full">


            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="product-area-title text-center">
                            <p class="text-uppercase">Some Featured Flights</p>
                            <h2 class="h1">Discover Hot Deals</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/c5.jpg" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4>Chandigarh-New Delhi</h4>
                                <p>Best fares for New Delhi </p>
                                <h5> Rs.6,822<span><a href="#" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>
        <!-- End Product Area -->
            
        </section>
        <!-- End Contact Area -->
        <!-- Start Cta Area -->
        <section class="cta-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 d-flex no-flex-xs justify-content-between align-items-center">
                        <h5 class="text-uppercase text-white">Not yet convinced with our quality?</h5>
                        <a href="#" class="primary-btn d-inline-flex text-uppercase text-white align-items-center">Contact Us<span class="lnr lnr-arrow-right"></span></a>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Cta Area -->