<?php

if(Zend_Auth::getInstance()->hasIdentity()){
    $link = HTTP_PATH.'index/booknow' ;                                 
}else{
    $link = HTTP_PATH.'user/login' ;
}

?>
        <!-- Start About Area -->
        <section id="home-boxs" class="section-full gray-bg">
            <div class="container">
                <div class="row">
                <?php foreach ($this->topProducts as $key => $value) { ?>
                                      
                    <div class="col-md-4">
                        <figure class="single-service">
                            <img src="<?php echo PUBLIC_PATH; ?>images/upload/products/medium/thum_medium_<?php echo $value["image"] ; ?>" class="img-fluid" alt="">
                            <figcaption class="text-center">
                                <h5 class="text-uppercase"><?php echo $value["title"] ; ?></h5>
                                <p><?php echo $value["description"] ; ?>
                                </p>
                                <a href="<?php echo $link ; ?>" class="primary-btn d-inline-flex align-items-center">BOOK NOW<span class="lnr lnr-arrow-right"></span></a>
                            </figcaption>
                        </figure>
                    </div>
                    
                <?php } ?>
                   
                </div>
            </div>
        </section>
        <!-- End About Area -->
        <!-- Start Product Area -->
        
        <section id="about-us" class="bg-dark section-full">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="section-title text-center">
                            <!-- <img src="<?php echo PUBLIC_PATH; ?>/images/front_end/ts3.png" class="img-fluid"> -->
                            <h6><p class="text-uppercase"><?php echo $this->whatweare["pageTitle"]; ?></p></h6>
                            <h3><?php echo $this->whatweare["content"]; ?></h3>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="services" class="title-bg section-full">


            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="product-area-title text-center">
                            <p class="text-uppercase">Some Featured Flights</p>
                            <h2 class="h1">Discover Hot Deals</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                 <?php foreach ($this->hotProducts as $key => $value) { ?>
                    <div class="col-lg-4 col-sm-6">
                        <div class="single-product">
                        <img src="<?php echo PUBLIC_PATH; ?>images/upload/products/medium/thum_medium_<?php echo $value["image"] ; ?>" />
                            <div class="icon">

                            </div>
                            <div class="desc">
                                <h4><?php echo $value["title"] ; ?></h4>
                                <p><?php echo $value["description"] ; ?> </p>
                                <h5> Rs.<?php echo $value["price"] ; ?><span><a href="<?php echo $link ; ?>" class="primary-btn d-inline-flex align-items-center">BOOK NOW</a></span></h5>
                            </div>
                        </div>
                    </div>
                <?php } ?>    
                   
                </div>
            </div>
        </section>
        <!-- End Product Area -->
            
        </section>
        <!-- End Contact Area -->
        <!-- Start Cta Area -->
        <section class="cta-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 d-flex no-flex-xs justify-content-between align-items-center">
                        <h5 class="text-uppercase text-white">Not yet convinced with our quality?</h5>
                        <a href="<?php echo HTTP_PATH.'index/contact' ; ?>" class="primary-btn d-inline-flex text-uppercase text-white align-items-center">Contact Us<span class="lnr lnr-arrow-right"></span></a>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Cta Area -->