		<!-- Start Banner Area -->

		<div class="owl-carousel owl-theme">
	    <div class="item">
	    	<section class="banner-area relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row justify-content-center align-items-center">
						<div class="col-lg-8">
							<div class="banner-content text-center">
								<p class="text-uppercase text-white">People don't take trips - trips take people</p>
								<h1 class="text-uppercase text-white">I love to travel, But hate to arrive</h1>
								<a href="#" class="primary-btn banner-btn">Book Now</a>
							</div>
						</div>
					</div>
				</div>
			</section>
	    </div>
	    <div class="item">
	    	<section class="banner-area relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row justify-content-center align-items-center">
						<div class="col-lg-8">
							<div class="banner-content text-center">
								<p class="text-uppercase text-white">We work hard, we result perfect</p>
								<h1 class="text-uppercase text-white">Crafting Digital Agency Experiences</h1>
								<a href="#" class="primary-btn banner-btn">Book Now</a>
							</div>
						</div>
					</div>
				</div>
			</section>
	    </div>
    
</div>
		<!-- End Banner Area -->