    <footer class="section-full">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-6">
            <div class="single-footer-widget">
              <h6 class="text-white text-uppercase mb-20">About Agency</h6>
              <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point </p>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="single-footer-widget">
              <h6 class="text-white text-uppercase mb-20">Navigation Links</h6>
              <div class="d-flex">
                <ul class="footer-nav">
                  
                  <li><a href="<?php echo HTTP_PATH.'index/aboutus' ; ?>">About Us</a></li>
                  <li><a href="<?php echo HTTP_PATH.'products/index' ; ?>">Deals</a></li>
                </ul>
                <ul class="ml-30 footer-nav">
                  <li><a target="_blank"  href="<?php echo HTTP_PATH.'page/tearmsandcondition' ; ?>">Terms</a></li>
                  <li><a href="<?php echo HTTP_PATH.'index/contact' ; ?>">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="single-footer-widget">
              <h6 class="text-white text-uppercase mb-20">Important</h6>
              <p>For business professionals caught between high OEM price and mediocre print and graphic output,</p>
              
            </div>
          </div>
          
        </div>
        <div class="footer-bottom d-flex justify-content-between align-items-center">
          <p class="footer-text m-0">Copyright &copy; 2017  |  All rights reserved.</p>
          <div class="footer-social d-flex align-items-center">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>

    
 
  </body>
</html>
