<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon-->
  <!-- Author Meta -->
  <meta name="author" content="CodePixar">
  <!-- Meta Description -->
  <meta name="description" content="">
  <!-- Meta Keyword -->
  <meta name="keywords" content="">
  <!-- meta character set -->
  <meta charset="UTF-8">
  <!-- Site Title -->
  <title>Flight Booking</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:300,500,600" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
<?php 
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/linearicons.css" );
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/owl.carousel.css" );
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/font-awesome.min.css" );
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/animate.css" );
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/bootstrap.css" );
      $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/front_end/main.css" );

echo $this->headStyle ();
echo $this->headLink ();
?>
<script src="<?php echo PUBLIC_PATH ?>js/front_end/vendor/jquery-2.2.4.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<?php 
    $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/bootstrap.min.js" );
    $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/jquery.ajaxchimp.min.js" );
    $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/jquery.sticky.js" );
    $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/owl.carousel.min.js" );
    $this->headScript ()->prependFile ( PUBLIC_PATH . "js/front_end/main.js" );

echo $this->headScript ();
echo $this->headMeta ();
echo $this->headTitle ();
?>

  </head>
  <body>
    <div id="top"></div>
    <!-- Start Header Area -->
    <header class="default-header">
      <div class="sticky-header">
        <div class="container">
          <div class="header-content d-flex justify-content-between align-items-center">
            <div class="logo">
              <a href="#top" class="smooth">
                <h2>Brothers Travels</h2>
              </a>
            </div>
            <div class="right-bar d-flex align-items-center">
              <nav class="d-flex align-items-center">
                <ul class="main-menu">
                  <li><a href="#">Home</a></li>
                  <li><a href="#">About</a></li>
                  <li><a href="#">Blog</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
                <a href="#" class="mobile-btn"><span class="lnr lnr-menu"></span></a>
              </nav>
              <div class="search relative d-none">
                <span class="lnr lnr-magnifier"></span>
                <form action="#" class="search-field">
                  <input type="text" placeholder="Search here" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search here'">
                  <button class="search-submit"><span class="lnr lnr-magnifier"></span></button>
                </form>
              </div>
              <div class="header-social d-none align-items-center">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header Area -->