<?php
$this->headTitle()->append($this->translate('Add Word'));

{
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/unsafewordsList.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
?>

<style>
<!--
#someID{
	margin-left:215px;
}
-->
</style>

<!-- Div for add new user list  -->
<div id='addNewregionDiv' class='wrap columns-2'>
<form name="addWords" id='addWords' method='POST' action='<?php echo HTTP_PATH; ?>admin/unsafewords/addword' enctype="multipart/form-data">
	<h1><?php echo $this->translate('Add New unsafe word'); ?></h1>
	<!--  <input type="button"  Value='<?php //echo $this->translate('Cancel'); ?>' name='addNew' class="btn ml10" onClick="window.location.href='<?php //echo HTTP_PATH; ?>admin/huntingregion'" />-->
	
	<div id='addNewUserDivInner' class="metabox-holder has-right-sidebar">
	<div id="post-body">
       <div>
         <div class="mainpage-content">
				
						<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title'); ?></strong></label></div>
                            <div class="mainpage-content-right control-group">
                                <div class="mainpage-content-right-inner-right-other help-inline"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <input type="text"  maxlength="54" name="Title" id="Title" placeholder="<?php echo $this->translate('Title'); ?>" class="span3">
                                </div>                        
                            </div>
                        </div>
					
					<div class="mainpage-content-line">
                    	<div class="mainpage-content-left"><label><strong><?php  echo $this->translate('Description'); ?></strong></label></div>
                    	<div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other" style="border-bottom-width: 0px; margin-bottom: 10px;" >
							<textarea class="input-xlarge mbot bbot ignore" id="Description" placeholder="<?php echo $this->translate('Description'); ?>" name="Description"  rows="3" ></textarea>
                    	</div>
                    </div>
                        </div>
                  
			<div class="clear"></div>
			
              
            
	  
            <div class="mainpage-content-colorbox">
            	<input type="hidden" name="contr" id="editcontr" value="update">
            	<button id='saveWords'  type="submit" class="btn btn-large btn-primary fl" ><?php echo $this->translate('Save'); ?></button>
				<a href="<?php echo HTTP_PATH; ?>admin/unsafewords/"  class="fl m10"><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
           
            </div>
      
            
            </form>
      </div>
            <!-- /poststuff -->
        
 <?php }?>
 