<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Product extends BaseProduct
{
	
	/**
	 * Author  Rohit
	 * @param varchar $params
	 * return Array
	 * Version 1.0
	 */
	
	public static function getProductlist($params){
		
		$srh = isset($params["searchtext"]) ? $params["searchtext"] : '';
		
		$data = Doctrine_Query::create()
				->select('g.title, g.description, cat.id, cat.name, g.created_at, g.updated_at')
				->from('product g')
				//->leftJoin('g.Image img')
				->leftJoin('g.Category cat')
				->where('g.title LIKE ?', "$srh%")
				->andWhere('g.deleted = 0')
				->orderBy('g.id DESC');
		
		return Zend_Json::encode(DataTable_Helper::generateDataTableResponse($data, 
				$params, 
				array("__identifier" => 'g.title', 'g.description', 'cat.name', 'g.created_at','g.updated_at'),
						array(),
						array()
				));
		exit();
		
		
		
	}
	
	
	/**
	 * Save gallery pics
	 * @author Raman
	 * @version 1.0
	 */
	
	public static function addProduct($category, $title, $description)
	{
		
		  $Obj = new Product();
		  $Obj->title = BackEnd_Helper_viewHelper::stripSlashesFromString($title);
		  //$Obj->price = BackEnd_Helper_viewHelper::stripSlashesFromString($price);
		  $Obj->categoryid = BackEnd_Helper_viewHelper::stripSlashesFromString($category);
		  $Obj->description = BackEnd_Helper_viewHelper::stripSlashesFromString($description);
		  
		  $Obj->save();
		  $lid = $Obj->id;
		  
		  /*$uploadPath = "images/upload/gallery/";
		  $imagobj = new Image();
		  $imagobj->itemId = $lid;
		  $imagobj->type = "IMGGLR";
		  $imagobj->ext = BackEnd_Helper_viewHelper::getImageExtension( $imgfile );
		  $imagobj->path = $uploadPath;
		  $imagobj->name = $imgfile;
		  $imagobj->save();*/
		return $lid ;
	}
	
	/**
	 * get to five category
	 * @param string $keyword
	 * @return array $data
	 * @author Raman
	 * @version 1.0
	 */
	public static function searchProduct($keyword) {
	
		$data = Doctrine_Query::create()->select('g.title as name')
		->from("product g")
		->where('g.deleted = 0')
		->andWhere("g.title LIKE ?", "%$keyword%")
		->orderBy("g.title ASC")
		->limit(5)
		->fetchArray();

		return $data;
	}
	
	/**
	 * Delete product photo by id
	 * @param integer $params
	 * @author Raman
	 * @version 1.0
	 */
	public static function deleteProduct($id) {
		$q = Doctrine_Query::create()->update('product g')
		->set('g.deleted', 1)
		->where('g.id=?', $id)
		->execute();
		return true;
		
	}
	
	/**
	 * Author  Raman
	 * @param integer $catId
	 * return Array
	 * Version 1.0
	 */
	
	public static function getproductForFront($catId){
	
		$data = Doctrine_Query::create()
		->select('g.*, cat.name,cat.description')
		->from('product g')
		// ->leftJoin('g.Image img')
		->leftJoin('g.Category cat')
		->where('g.categoryid=?', $catId)
		->andWhere('cat.deleted = 0')
		->orderBy('g.id DESC')
		//->getSqlQuery();
		->fetchArray();
		return $data;
	}
	
}